# Generated by Django 3.1.7 on 2021-03-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20210310_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='long_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_code',
            field=models.CharField(max_length=16),
        ),
    ]
