# Generated by Django 3.1.7 on 2021-03-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0003_auto_20210310_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_code',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
