# Generated by Django 3.1.7 on 2021-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0005_auto_20210311_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='clicked',
            field=models.IntegerField(default=0),
        ),
    ]
