# Generated by Django 3.1.7 on 2021-03-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0007_auto_20210311_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='clicked',
        ),
        migrations.AddField(
            model_name='urls',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
