# Generated by Django 3.1.7 on 2021-03-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0008_auto_20210312_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='click',
            field=models.IntegerField(null=True),
        ),
    ]
