# Generated by Django 3.1.7 on 2021-03-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0009_urls_click'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='click',
        ),
    ]
