# Generated by Django 3.1.7 on 2021-03-09 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery_item',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
