# Generated by Django 3.1.7 on 2021-03-08 22:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 3, 8, 22, 39, 17, 295699, tzinfo=utc))),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
