# Generated by Django 3.1.7 on 2021-03-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short_urls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcode',
            old_name='url',
            new_name='url_long',
        ),
        migrations.RenameField(
            model_name='shortcode',
            old_name='code',
            new_name='url_short',
        ),
    ]
