# Generated by Django 3.1.7 on 2021-03-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField()),
                ('food_item', models.CharField(max_length=50)),
                ('bought', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
