# Generated by Django 3.1.7 on 2021-03-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210316_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
