# Generated by Django 3.1.7 on 2021-03-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shorten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_text', models.CharField(max_length=6)),
                ('url_text', models.TextField(max_length=200)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
