# Generated by Django 3.1.7 on 2021-03-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
