# Generated by Django 3.1.7 on 2021-03-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210317_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
